name: Deploy to Yandex Cloud
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Sync build folder
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YANDEX_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YANDEX_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ru-central1
        run: |
          aws s3 sync ./build/ s3://${{ secrets.YANDEX_BUCKET_NAME }}/build/ \
            --endpoint-url=https://storage.yandexcloud.net \
            --delete \
            --size-only
      - name: Sync media folder
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YANDEX_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YANDEX_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ru-central1
        run: |
          aws s3 sync ./media/ s3://${{ secrets.YANDEX_BUCKET_NAME }}/media/ \
            --endpoint-url=https://storage.yandexcloud.net \
            --delete \
            --size-only
